// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/refynehq/refyne-backend/internal/api"
	"github.com/refynehq/refyne-backend/internal/bootstrap"
	"github.com/refynehq/refyne-backend/internal/config"
	"github.com/refynehq/refyne-backend/internal/database"
	"github.com/refynehq/refyne-backend/internal/domains/ai"
	auth2 "github.com/refynehq/refyne-backend/internal/domains/auth"
	auth4 "github.com/refynehq/refyne-backend/internal/domains/auth/handler"
	"github.com/refynehq/refyne-backend/internal/domains/auth/repository"
	auth3 "github.com/refynehq/refyne-backend/internal/domains/auth/services"
	"github.com/refynehq/refyne-backend/internal/domains/context"
	"github.com/refynehq/refyne-backend/internal/domains/email"
	"github.com/refynehq/refyne-backend/internal/domains/email/jobs"
	"github.com/refynehq/refyne-backend/internal/domains/email/service"
	"github.com/refynehq/refyne-backend/internal/domains/notification"
	"github.com/refynehq/refyne-backend/internal/domains/otto"
	"github.com/refynehq/refyne-backend/internal/domains/subscription"
	config2 "github.com/refynehq/refyne-backend/internal/domains/subscription/config"
	"github.com/refynehq/refyne-backend/internal/domains/subscription/handler"
	"github.com/refynehq/refyne-backend/internal/domains/subscription/repository"
	"github.com/refynehq/refyne-backend/internal/domains/subscription/services"
	user4 "github.com/refynehq/refyne-backend/internal/domains/user"
	"github.com/refynehq/refyne-backend/internal/domains/user/core/repository"
	user3 "github.com/refynehq/refyne-backend/internal/domains/user/handler"
	user2 "github.com/refynehq/refyne-backend/internal/domains/user/services"
	"github.com/refynehq/refyne-backend/internal/domains/workspace"
	"github.com/refynehq/refyne-backend/internal/shared/audit"
	"github.com/refynehq/refyne-backend/internal/shared/device"
	"github.com/refynehq/refyne-backend/internal/shared/handlerRegistry"
	"github.com/refynehq/refyne-backend/internal/shared/redis"
	"github.com/refynehq/refyne-backend/internal/shared/river"
	"github.com/refynehq/refyne-backend/internal/shared/validation"
	"github.com/refynehq/refyne-backend/pkg/logging"
)

// Injectors from wire.go:

func InitializeApp() (*bootstrap.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	pool, err := database.NewPool()
	if err != nil {
		return nil, err
	}
	coreUserRepository := user.NewCoreUserRepository(db)
	passwordResetRepository := auth.NewPasswordResetRepository(db)
	verificationRepository := auth.NewVerificationRepository(db)
	accountSecurityRepository := auth.NewAccountSecurityRepository(db)
	smtpService := service.NewSMTPService(configConfig)
	emailService, err := service.NewEmailService(smtpService)
	if err != nil {
		return nil, err
	}
	emailWorker := jobs.NewEmailWorker(emailService)
	workerDependancies := riverqueue.NewWorkerDependancies(emailWorker)
	riverService, err := riverqueue.NewRiverService(pool, workerDependancies)
	if err != nil {
		return nil, err
	}
	client := riverqueue.ProvideRiverClientAny(riverService)
	auditLogger := audit.ProvideAuditLogger(db)
	logger := logging.NewLogger()
	deviceSessionService := device.NewDeviceSessionService(db, logger)
	validator := validation.NewValidator()
	string2 := auth2.ProvideFrontendURL(configConfig)
	authService := auth3.NewAuthService(coreUserRepository, passwordResetRepository, verificationRepository, accountSecurityRepository, emailService, client, auditLogger, deviceSessionService, validator, string2)
	authHandler := auth4.NewAuthHandler(authService)
	authRegistry := auth2.NewAuthRegistry(authHandler)
	settingsRepository := user2.NewSettingsRepository(db)
	userService := user2.NewUserService(coreUserRepository, settingsRepository)
	userHandler := user3.NewUserHandler(userService)
	userRegistry := user4.NewUserRegistry(userHandler)
	aiRegistry := ai.NewAIRegistry()
	contextRegistry := context.NewContextRegistry()
	emailRegistry := email.NewEmailRegistry()
	notificationRegistry := notification.NewNotificationRegistry()
	ottoRegistry := otto.NewOttoRegistry()
	workspaceRegistry := workspace.NewWorkspaceRegistry()
	paddleConfig, err := config2.NewPaddleConfig(logger)
	if err != nil {
		return nil, err
	}
	paddleService, err := services.NewPaddleService(paddleConfig)
	if err != nil {
		return nil, err
	}
	subscriptionRepository := repository.NewSubscriptionRepository(db)
	webhookService := services.NewWebhookService(subscriptionRepository, logger)
	subscriptionHandler := handler.NewSubscriptionHandler(paddleService, webhookService, subscriptionRepository)
	subscriptionRegistry := subscription.NewSubscriptionRegistry(subscriptionHandler)
	handlerRegistry := handlerregistry.NewHandlerRegistry(authRegistry, userRegistry, aiRegistry, contextRegistry, emailRegistry, notificationRegistry, ottoRegistry, workspaceRegistry, subscriptionRegistry)
	redisClient, err := redis.NewRedisClient(configConfig)
	if err != nil {
		return nil, err
	}
	client2 := redis.ProvideRedisClient(redisClient)
	engine := api.NewRouter(handlerRegistry, db, client2)
	app, err := bootstrap.NewApp(configConfig, db, pool, engine, logger, riverService, client2)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(config.ProviderSet, database.ProviderSet, logging.ProviderSet, redis.ProviderSet, riverqueue.ProviderSet, handlerregistry.ProviderSet, ai.ProviderSet, auth2.ProviderSet, context.ProviderSet, email.ProviderSet, notification.ProviderSet, otto.ProviderSet, subscription.ProviderSet, user4.ProviderSet, workspace.ProviderSet, api.ProviderSet, bootstrap.ProviderSet)
