// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/refynehq/refyne-backend/internal/api"
	"github.com/refynehq/refyne-backend/internal/bootstrap"
	"github.com/refynehq/refyne-backend/internal/config"
	"github.com/refynehq/refyne-backend/internal/database"
	auth3 "github.com/refynehq/refyne-backend/internal/domain/auth"
	auth2 "github.com/refynehq/refyne-backend/internal/domain/auth/handler"
	"github.com/refynehq/refyne-backend/internal/domain/auth/services"
	user2 "github.com/refynehq/refyne-backend/internal/domain/user"
	"github.com/refynehq/refyne-backend/internal/domain/user/repository"
	"github.com/refynehq/refyne-backend/internal/shared/registry"
	"github.com/refynehq/refyne-backend/internal/shared/river"
	"github.com/refynehq/refyne-backend/pkg/logging"
)

// Injectors from wire.go:

func InitializeApp() (*bootstrap.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	pool, err := database.NewPool()
	if err != nil {
		return nil, err
	}
	coreUserRepository := user.NewCoreUserRepository(db)
	authService := auth.NewAuthService(coreUserRepository)
	authHandler := auth2.NewAuthHandler(authService)
	handlerRegistry := registry.NewHandlerRegistry(authHandler)
	engine := api.NewRouter(handlerRegistry)
	workerDependancies := riverqueue.NewWorkerDependancies()
	riverService, err := riverqueue.NewRiverService(pool, workerDependancies)
	if err != nil {
		return nil, err
	}
	app := bootstrap.NewApp(configConfig, db, pool, engine, riverService)
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(config.ProviderSet, database.ProviderSet, logging.ProviderSet, riverqueue.ProviderSet, registry.ProviderSet, user2.ProviderSet, auth3.ProviderSet, api.ProviderSet, bootstrap.ProviderSet)
